services:
  apache:
    build:
      context: .
      dockerfile: "../vendor/mulertech/docker-tests/Dockerfile"
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PHP_IMAGE: "${PHP_IMAGE}"
    container_name: ${CONTAINER_NAME_APACHE}
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "../:/var/www/html"
    environment:
      - PHP_CS_FIXER_IGNORE_ENV=1
    networks:
      - default

networks:
  default:
    driver: bridge